### ISSUE TITLE
Add to documentation for location of systemd service configuration so the user can acquire the generated master key

### ISSUE THREAD

**Issue by jake-designori** [meilisearch/meilisearch-digitalocean#63]
I haven't been in a Debian system for about a year so I was a bit rusty, but I was expecting the start up script to tell me where to get the master key from or tell me what master key it generated. I finally found this in the documentation: https://docs.meilisearch.com/running-production/#step-2-run-meilisearch-as-a-service, which I then assumed the DO version would be running as a service like most of the one-clicks. 

Service configuration location: `/etc/systemd/system/meilisearch.servcie`

Control service: `systemctl start/stop/restart meilisearch`

This will help us noobs. Thanks!

**Comment by eskombro** [comment]
Hey @jake-designori 

Thanks for this issue. When you run a MeiliSearch droplet in the DigitalOcean marketplace for 1 click installations you can have two different situations:

1. You just create a droplet. This will launch a MeiliSearch in "development" environment and no Master Key is set.
2. You connect via SSH to your droplet after creating it, which triggers automatically a script that will ask you if you want to set a production environment. This script will ask you if you want a Master Key, and if so, if you prefer to add yours or if you want an automatically generated one. When you have answered this, the key will be set and the information is logged in the console, telling you explicitly what your key is.

Following this thought, it seems that you shouldn't be able to set a Master Key without knowing it.

But as you point out, nothing has been done to let the user "Retrieve this key afterwards.

Will have this in mind, because this script might need be worked on soon, and it will be better documented

> Service configuration location: /etc/systemd/system/meilisearch.servcie

Just wanted to point out that there is a typo in there, just in case someone else comes and read this.

Service location is:

```
/etc/systemd/system/meilisearch.service
```
